version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

  # Environment variables (quoted value to avoid YAML parsing issues)
  environment:
    GH_PAT_TOKEN: "$GITHUB_PAT_TOKEN"  # Added quotes around the value

  jobs:
    pre_build:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - python automation/fetch_remote.py  # Removed "$REPO_NAME" (not needed for Read the Docs builds)
      - python automation/cleanup_version.py
      - python automation/generate_nav.py  # Fixed lowercase filename

mkdocs:
  configuration: mkdocs.yml