version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - python automation/fetch_remote.py "$REPO_NAME"
      - python automation/generate_TOC.py
      - python automation/generate_nav.py  # Add the call to your nav generation script

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
