version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_build:
      - python3 automation/fetch_remote.py "$REPO_NAME"
      - python3 automation/generate_TOC.py

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
