version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

  # Environment variables
  environment:
    GH_PAT_TOKEN: $GITHUB_PAT_TOKEN  # Matches Read the Docs environment variable

  jobs:
    pre_build:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - python automation/fetch_remote.py "$REPO_NAME"
      - python automation/cleanup_version.py
      - python automation/generate_NAV.py

mkdocs:
  configuration: mkdocs.yml