version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

mkdocs:
  configuration: mkdocs.yml