version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

  # Add environment variables
  environment:
    GH_PAT_TOKEN: $GH_PAT_TOKEN  # This will be set in the Read the Docs project settings

  jobs:
    pre_build:
      - python -m pip install --upgrade pip
      - pip install requests pyyaml
      - python automation/fetch_remote.py "$REPO_NAME"
      - python automation/cleanup_version.py
      - python automation/generate_nav.py

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt