site_name: "Unified Project Documentation"
repo_url: "https://github.com/SHINO-01/RTD_MONO_REPO"
edit_uri: "edit/main/docs/"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - search.highlight
    - content.code.copy
    - content.action.edit
plugins:
  - search
  - mkdocs-gen-files
  - mkdocs-section-index
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Projects: projects/index.md
