site_name: "Unified Project Documentation"
site_description: "Centralized documentation for multiple projects"
theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  language: en

extra:
  favicon: assets/img/favicon.ico

repo_url: "https://github.com/SHINO-01/RTD_MONO_REPO"

plugins:
  - awesome-pages  # Automatically organizes navigation based on folder structure
  - search
  - gen-files:
      scripts:
        - automation/generate_TOC.py

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - Home: docs/index.md
