name: Fetch Documentation Updates

on:
  repository_dispatch:
    types: [docs_updated]

jobs:
  fetch-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch_docs.py
        run: |
          python automation/fetch_remote.py

      - name: Run cleanup_versions.py
        run: |
          python automation/cleanup_version.py

      - name: Run generate_TOC.py
        run: |
          python automation/generate_TOC.py

      - name: Commit and push updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated Docs Update via Webhook"
            git push
          else
            echo "No changes to commit."
          fi
