name: Fetch Documentation Updates

on:
  repository_dispatch:
    types: [docs_updated]

jobs:
  fetch-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Fetch documentation from triggering repo
        env:
          GITHUB_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}  # Updated to match Read the Docs
          REPO_NAME: ${{ github.event.client_payload.repository }}
        run: |
          python automation/fetch_remote.py "$REPO_NAME"

      - name: Run cleanup_versions.py
        run: python automation/cleanup_version.py

      - name: Generate Navigation Structure
        run: python automation/generate_NAV.py

      - name: Commit and push updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated Docs Update for $REPO_NAME"
            git push
          else
            echo "No changes to commit."
          fi